name: string_story
description: "In-app story board and editor for your translations"
version: 0.0.4
homepage: https://github.com/vishna/string_story/tree/main/packages/string_story

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flag: ^7.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  simple_rich_text: ^2.0.49
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  synchronized: ^3.4.0
  email_validator: ^3.0.0
  wolt_modal_sheet: ^0.11.0
  scrollview_observer: ^1.25.1
  sliver_tools: ^0.2.12
  device_frame: ^1.4.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.8.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
